import { RetrofitOption } from './types';
import { RETROFIT_UNIT_ASSUMPTIONS, CENTRAL_RETROFIT_ASSUMPTIONS } from './assumptions';

export const FULL_RETROFIT_CATALOG: RetrofitOption[] = [
  {
    id: 'EXTERNAL_SHADING',
    name: 'External Solar Louvers & Shading Devices',
    category: 'Solar Control & Envelope Shading',
    description: 'Exterior architectural fins and motorized louvers that block direct solar radiation before entering glazing.',
    detailedSpecs: 'Extruded aluminum louvers installed on South/East facades. Blocks up to 82% of direct solar heat gain while retaining natural daylighting.',
    thermalImpact: 'HIGH',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.EXTERNAL_SHADING.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.EXTERNAL_SHADING.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.EXTERNAL_SHADING.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0, // Calculated dynamically from building window area
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.EXTERNAL_SHADING.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'MODERATE',
    applicableWeaknesses: ['SOUTH_FACADE', 'HIGH_SOLAR_EXPOSURE', 'WINDOWS', 'SOLAR_GLARE'],
    assumptions: [
      'Assumes installation on South and East perimeter curtain wall elevations.',
      'Unit cost range: $12 to $22 per sq ft of treated glass area.',
    ],
    iconName: 'SunMedium',
  },
  {
    id: 'ROOF_INSULATION',
    name: 'Continuous High-Performance Roof Insulation (R-20+)',
    category: 'Roof Thermal Envelope',
    description: 'Polyisocyanurate rigid foam insulation board under elastomeric roof membrane to block conductive heat transfer.',
    detailedSpecs: 'Increases roof thermal resistance from baseline R-8.5 to R-28.5. Dramatically reduces top-floor thermal absorption.',
    thermalImpact: 'HIGH',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.ROOF_INSULATION.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.ROOF_INSULATION.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.ROOF_INSULATION.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0,
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.ROOF_INSULATION.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'COMPLEX',
    applicableWeaknesses: ['ROOF', 'POOR_INSULATION', 'DARK_ROOF_MEMBRANE', 'TOP_FLOOR_HEAT'],
    assumptions: [
      'Assumes continuous rigid polyiso insulation installed above structural deck.',
      'Unit cost range: $5.50 to $11.00 per sq ft of roof area.',
    ],
    iconName: 'Layers',
  },
  {
    id: 'COOL_ROOF',
    name: 'High-Albedo Elastomeric Cool Roof Coating (SRI 108)',
    category: 'Cool Surface Barrier',
    description: 'Seamless white elastomeric reflective coating reflecting 88% of solar radiation.',
    detailedSpecs: 'Solar Reflectance Index (SRI) of 108. Drops peak roof surface temperature from 56.8°C down to near ambient 32.1°C.',
    thermalImpact: 'HIGH',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.COOL_ROOF.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.COOL_ROOF.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.COOL_ROOF.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0,
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.COOL_ROOF.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'EASY',
    applicableWeaknesses: ['ROOF', 'DARK_ROOF_MEMBRANE', 'URBAN_HEAT_ISLAND', 'HIGH_ROOF_LST'],
    assumptions: [
      'Applied directly over existing clean membrane with primer coat.',
      'Unit cost range: $3.00 to $5.50 per sq ft of roof area.',
    ],
    iconName: 'ShieldCheck',
  },
  {
    id: 'SOLAR_GLAZING',
    name: 'Spectrally Selective Nano-Ceramic Window Film',
    category: 'Fenestration Tinting',
    description: 'Advanced nano-ceramic film rejecting 78% solar heat gain while maintaining 70% visible light transmission.',
    detailedSpecs: 'Reduces Solar Heat Gain Coefficient (SHGC) from clear 0.65 down to 0.22. Prevents perimeter zone hot spots.',
    thermalImpact: 'MEDIUM',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.SOLAR_GLAZING.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.SOLAR_GLAZING.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.SOLAR_GLAZING.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0,
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.SOLAR_GLAZING.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'EASY',
    applicableWeaknesses: ['WINDOWS', 'SOUTH_FACADE', 'HIGH_SHGC', 'PERIMETER_GLARE'],
    assumptions: [
      'Internal surface application on exterior glass panes.',
      'Unit cost range: $5.50 to $9.50 per sq ft of window area.',
    ],
    iconName: 'SunMedium',
  },
  {
    id: 'HVAC_UPGRADE',
    name: 'AI Predictive HVAC Optimization & Variable Speed Drives',
    category: 'Mechanical Systems',
    description: 'AI-driven dynamic chiller sequencing, VFD pump controls & setpoint automation.',
    detailedSpecs: 'Integrates FortyGuard microclimate forecasts into Building Management System (BMS) for load prediction.',
    thermalImpact: 'HIGH',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.HVAC_UPGRADE.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.HVAC_UPGRADE.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.HVAC_UPGRADE.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0,
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.HVAC_UPGRADE.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'MODERATE',
    applicableWeaknesses: ['HVAC', 'LOW_COP', 'AGED_CHILLERS', 'HVAC_EXHAUST_PLUME'],
    assumptions: [
      'Retrofitted onto central chiller plant and BMS controllers.',
      'Unit cost range: $1.80 to $3.50 per sq ft of gross building area.',
    ],
    iconName: 'Cpu',
  },
  {
    id: 'VEGETATION',
    name: 'Biosolar Green Roof & Urban Canopy Infrastructure',
    category: 'Green Infrastructure',
    description: 'Sedum vegetation substrate layer providing evapotranspiration cooling & thermal mass.',
    detailedSpecs: '4-inch engineered soil substrate with drought-tolerant sedum varieties. Eliminates ambient heat island radiation.',
    thermalImpact: 'HIGH',
    energyImpactRange: {
      minReductionPct: RETROFIT_UNIT_ASSUMPTIONS.VEGETATION.minEnergyCutPct,
      maxReductionPct: RETROFIT_UNIT_ASSUMPTIONS.VEGETATION.maxEnergyCutPct,
      expectedTempReductionC: RETROFIT_UNIT_ASSUMPTIONS.VEGETATION.tempDropC,
    },
    estimatedCostRange: {
      minUSD: 0,
      maxUSD: 0,
      unitLabel: RETROFIT_UNIT_ASSUMPTIONS.VEGETATION.unitLabel,
      costDisclaimer: CENTRAL_RETROFIT_ASSUMPTIONS.costDisclaimerLabel,
    },
    implementationComplexity: 'COMPLEX',
    applicableWeaknesses: ['ROOF', 'URBAN_HEAT_ISLAND', 'HIGH_ROOF_LST', 'STORMWATER_HEAT'],
    assumptions: [
      'Requires structural load check for 25 lbs/sq ft wet soil weight.',
      'Unit cost range: $16.00 to $28.00 per sq ft of roof area.',
    ],
    iconName: 'TreeSprout',
  },
];
